name: 'Trigger workflow and wait'
description: 'This action triggers a workflow in another repository and waits for the result.'
inputs:
  GITHUB_TOKEN:
    description: 'Auth token for New Expensify Github; necessary for accessing Octokit.'
    required: true

runs:
  using: 'node16'
  main: './index.js'
