name: Test for sth

on:
  workflow_dispatch:

jobs:
  CLA:
    runs-on: ubuntu-latest
    # This job only runs for pull request comments or pull request target events (not issue comments)
    # It does not run for pull requests created by OSBotify
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          repository: staszekscp/pokedex_fork
          fetch-depth: 0
      - name: run
        run: |
          chmod +x ./script.sh
          ./script.sh
        
